"""LaTeX utilities: templates, project structure, cleanup.

Follows the ARIS paper-write template conventions:
    - venue-specific documentclass
    - math_commands.tex for shared notation
    - references.bib (filtered to cited entries only)
    - sections/ directory with one file per section
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Optional

# Venue -> (documentclass line, packages, bib style, citation command)
VENUE_TEMPLATES: Dict[str, Dict[str, str]] = {
    "ICLR": {
        "documentclass": r"\documentclass{article}",
        "style_package": r"\usepackage{iclr2026_conference,times}",
        "cite_cmd": r"\citep{}",
        "bib_style": "plainnat",
        "notes": "natbib citation (\\citep/\\citet)",
    },
    "NEURIPS": {
        "documentclass": r"\documentclass{article}",
        "style_package": r"\usepackage[preprint]{neurips_2025}",
        "cite_cmd": r"\citep{}",
        "bib_style": "plainnat",
        "notes": "natbib citation (\\citep/\\citet)",
    },
    "ICML": {
        "documentclass": r"\documentclass[accepted]{icml2025}",
        "style_package": r"\usepackage{icml2025}",
        "cite_cmd": r"\citep{}",
        "bib_style": "plainnat",
        "notes": "natbib citation (\\citep/\\citet)",
    },
    "IEEE_JOURNAL": {
        "documentclass": r"\documentclass[journal]{IEEEtran}",
        "style_package": r"\usepackage{cite}",
        "cite_cmd": r"\cite{}",
        "bib_style": "IEEEtran",
        "notes": "IEEE uses \\cite (numeric), NOT natbib",
    },
    "IEEE_CONF": {
        "documentclass": r"\documentclass[conference]{IEEEtran}",
        "style_package": r"\usepackage{cite}",
        "cite_cmd": r"\cite{}",
        "bib_style": "IEEEtran",
        "notes": "IEEE uses \\cite (numeric), NOT natbib",
    },
}

DEFAULT_TEMPLATE = VENUE_TEMPLATES["ICLR"]


def venue_key(venue: str) -> str:
    return venue.strip().upper()


def is_natbib(venue: str) -> bool:
    """True for ML venues using \\citep/\\citet; False for IEEE numeric \\cite."""
    key = venue_key(venue)
    return key in ("ICLR", "NEURIPS", "ICML", "CVPR", "ACL", "AAAI", "ACM")


def citation_command(venue: str) -> str:
    """Return the citation macro form appropriate for the venue."""
    return r"\citep{}" if is_natbib(venue) else r"\cite{}"


def build_main_tex(
    title: str,
    venue: str,
    section_filenames: List[str],
    anonymous: bool = True,
    bibliography: str = "references",
    max_pages_hint: Optional[int] = None,
) -> str:
    """Build the master main.tex that \\input{}s each section file.

    Args:
        title: paper title.
        venue: target venue key.
        section_filenames: ordered list of section .tex filenames under sections/.
        anonymous: whether to use anonymous author block.
        bibliography: basename of the .bib file (without extension).
        max_pages_hint: optional venue page limit, embedded as a comment.
    """
    key = venue_key(venue)
    tpl = VENUE_TEMPLATES.get(key, DEFAULT_TEMPLATE)

    author_block = r"\author{Anonymous Authors}" if anonymous else r"\author{Your Name\\Your Affiliation\\your@email.com}"

    inputs = "\n".join(
        rf"    \input{{sections/{name}}}" for name in section_filenames
    )

    natbib = r"\usepackage{natbib}" if is_natbib(venue) else r"\usepackage{cite}"

    page_limit_comment = (
        f"% Page limit: {max_pages_hint} pages main body (to end of Conclusion; "
        f"references/appendix {'counted' if not is_natbib(venue) else 'not counted'} for {key}).\n"
        if max_pages_hint
        else ""
    )

    return rf"""% {title} -- generated by the Writing Agent
% Venue: {key}
{page_limit_comment}%
{tpl['documentclass']}
\usepackage{{amsmath,amssymb,amsfonts}}
\usepackage{{graphicx}}
\usepackage{{booktabs}}
\usepackage{{multirow}}
\usepackage[colorlinks=true,linkcolor=blue,citecolor=blue,urlcolor=blue]{{hyperref}}
\usepackage{{cleveref}}
{natbib}
{tpl['style_package']}
\usepackage{{algorithm}}
\usepackage{{algorithmic}}

% Shared math notation
\input{{math_commands}}

\title{{{title}}}
{author_block}

\begin{{document}}
\maketitle

{inputs}

\bibliographystyle{{{tpl['bib_style']}}}
\bibliography{{{bibliography}}}

\end{{document}}
"""


def build_math_commands(extra: str = "") -> str:
    """Generate math_commands.tex with shared notation macros."""
    base = r"""% math_commands.tex -- shared notation (edit for paper-specific macros)
\newcommand{\R}{\mathbb{R}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\V}{\mathrm{Var}}
\newcommand{\given}{\,|\,}
\DeclareMathOperator*{\argmin}{arg\,min}
\DeclareMathOperator*{\argmax}{arg\,max}
\DeclareMathOperator{\sgn}{sgn}
\newcommand{\norm}[1]{\left\lVert #1 \right\rVert}
\newcommand{\abs}[1]{\left\lvert #1 \right\rvert}
\newcommand{\inner}[2]{\left\langle #1, #2 \right\rangle}
"""
    if extra.strip():
        base += "\n% Paper-specific notation\n" + extra.strip() + "\n"
    return base


def wrap_section(filename: str, body: str) -> str:
    """Wrap a body in the appropriate \\section command based on filename.

    Handles abstract specially (no \\section) and the appendix.
    """
    body = body.strip()
    base = Path(filename).stem  # e.g. 0_abstract, 3_method
    if base.endswith("abstract") or base.startswith("0"):
        return body + "\n"
    if "appendix" in base:
        return "\\appendix\n\n" + body + "\n"
    # derive a section title from the filename: 1_introduction -> Introduction
    parts = base.split("_", 1)
    title = parts[1].replace("_", " ").title() if len(parts) > 1 else base.replace("_", " ").title()
    return f"\\section{{{title}}}\n{body}\n"


def create_project_structure(paper_dir: Path, sections_dir: Path) -> None:
    """Create the paper/ directory tree."""
    paper_dir.mkdir(parents=True, exist_ok=True)
    sections_dir.mkdir(parents=True, exist_ok=True)


def read_all_sections(paper_dir: Path) -> str:
    """Concatenate all section files in filename order for review prompts."""
    sections_dir = paper_dir / "sections"
    if not sections_dir.exists():
        return ""
    parts = []
    for f in sorted(sections_dir.glob("*.tex")):
        if f.name in ("math_commands.tex",):
            continue
        parts.append(f"% === {f.name} ===\n{f.read_text(encoding='utf-8', errors='ignore')}")
    return "\n\n".join(parts)


def extract_citation_keys(tex_text: str) -> List[str]:
    """Extract unique citation keys from \\cite{...}, \\citep{...}, \\citet{...}."""
    keys = set()
    for m in re.finditer(r"\\cite[a-zA-Z]*\{([^}]*)\}", tex_text):
        for k in m.group(1).split(","):
            k = k.strip()
            if k:
                keys.add(k)
    return sorted(keys)


def ensure_labels_unique(tex_text: str) -> List[str]:
    """Return list of duplicate \\label values (blocking in final checks)."""
    labels = re.findall(r"\\label\{([^}]*)\}", tex_text)
    seen = {}
    dups = []
    for lab in labels:
        if lab in seen:
            dups.append(lab)
        seen[lab] = True
    return sorted(set(dups))
